/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CityTemperature: typeof import('./src/components/widgets/CityTemperature.vue')['default']
    DailyForecast: typeof import('./src/components/widgets/DailyForecast.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Header: typeof import('./src/components/Header.vue')['default']
    HourlyForcast: typeof import('./src/components/widgets/HourlyForcast.vue')['default']
    Indicatorcs: typeof import('./src/components/widgets/Indicatorcs.vue')['default']
    Indicators: typeof import('./src/components/widgets/Indicators.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Widgets: typeof import('./src/components/widgets/Widgets.vue')['default']
  }
}
